[project]
name = "lmx2db"
version = "0.1.0"
description = "A tool to convert LMX files to database format"
requires-python = ">=3.10"
dependencies = [
    "pre-commit>=4.5.1",
    "yamllint>=1.37.1",
]
